server {
    listen 8080;
    server_name _;
    location ~ ^/\.well-known/acme-challenge/[0-9A-Za-z_-]{43}/?$ {
        limit_except GET { deny all; }
        proxy_pass http://certlord:8666;
        proxy_set_header Authorization "";
        proxy_set_header Host $host;
    }
    location / { return 404; }
}
